### ISSUE TITLE
error rsync code 23 

### ISSUE THREAD

**Issue by aragon5956** [RsyncProject/rsync#653]
hello, 
I downloaded rsync from apt , and I got a error 23: `rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main. c(1338) [sender=3.2.7] `is this related to the remote repo owner being www-data, and I connect to the server with a different user? , if so how to avoid having the error

regards

**Comment by aragon5956** [comment]
I found the case by myself, yes it is related , but I don’t see a way around the pb.

my bash script is :

```
#!/bin/bash

# Définir le mot de passe pour sshpass
PASSWORD="AAA"

# Définir l'utilisateur et l'hôte pour SSH
SSH_USER="ale"
SSH_HOST="x.x.x.x"

# Définir le chemin du projet distant
REMOTE_PATH="/var/www/webProject"

# Nettoyer le cache local
php bin/console cache:clear

# Synchroniser les fichiers avec rsync
sshpass -p "$PASSWORD" rsync -avz --copy-links\
    --exclude=".git/" \
    --exclude="connection.sh" \
    --exclude="deploy.sh" \
    --exclude=".env.local" \
    --exclude="download.sh" \
    --exclude="node_modules/" \
    --exclude="vendor/" \
    ./ "$SSH_USER@$SSH_HOST:$REMOTE_PATH/"


# Exécuter la commande de nettoyage de cache sur le serveur distant
sshpass -p "$PASSWORD" ssh -t "$SSH_USER@$SSH_HOST" "cd $REMOTE_PATH && php bin/console cache:clear --env=prod --no-debug"

# Définir l'utilisateur HTTP (normalement www-data pour Nginx)
#HTTPDUSER="www-data"

# Appliquer les ACL localement (notez que cela nécessite sudo, donc le mot de passe sera demandé)
#sudo setfacl -R -m u:"$HTTPDUSER":rwX -m u:$(whoami):rwX var

#echo "Déploiement terminé avec succès!"
```

could you help me ?

**Comment by aragon5956** [comment]
i found better solution here :  https://forum.ansible.com/t/impossible-to-transfer-data-with-synchronize-rsync-code-12-io-c-232/10685/5

with ansible and this  playbook : 
```

- hosts: servers
  become: yes
  vars:
    symfony_root: /var/www/AnalyticaTechCode
    local_project_root: "/home/alexandre/Documents/AnalyticaTechCode"

  tasks:
    - name: Ensure directory exists
      file:
        path: "{{ symfony_root }}"
        state: directory
        owner: alexandre
        group: www-data
        mode: '0755'

    - name: Ensure correct permissions on symfony_root
      file:
        path: "{{ symfony_root }}"
        state: directory
        owner: alexandre
        group: www-data
        mode: '0775'
        recurse: yes

    - name: Synchronize project files
      ansible.posix.synchronize:
        src: "{{ local_project_root }}/"
        dest: "{{ symfony_root }}"
        rsync_opts:
          - "--exclude=.git"
      delegate_to: localhost
      become: no

    - name: Set final permissions
      file:
        path: "{{ symfony_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes
```
if someone has a question let them say so 

Regards
