### ISSUE TITLE
error to transfer files with rsync and ansible

### ISSUE THREAD

**Issue by aragon5956** [RsyncProject/rsync#661]
hello , 
i can't transfer my files to my web server, with ansible and rsync ,i don't know iof it's linked to `23 error`, and permissions problem here this my playbook.yml: 
```

   - name: Synchronize project files
      synchronize:
        src: "{{ local_project_root }}/"
        dest: "{{ symfony_root }}"
        archive: yes
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=var/cache/*"
          - "--exclude=var/log/*"
          - "--exclude=.env.local"
          - "--exclude=vendor/"
          - "--exclude=node_modules/"
          - "--exclude=ansible/"
        use_ssh_args: yes
      become: no
      delegate_to: localhost

    - name: Set final permissions
      file:
        path: "{{ symfony_root }}"
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes
```
i installed rsync , on my remote webServer version is : 
```

(env) alexandre@ubuntu:~/rsync$ rsync --version
rsync  version 3.3.0-22-g0902b52f  protocol version 31
Copyright (C) 1996-2024 by Andrew Tridgell, Wayne Davison, and others.
Web site: https://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, symlinks, symtimes, hardlinks, hardlink-specials,
    hardlink-symlinks, IPv6, atimes, batchfiles, inplace, append, no ACLs,
    xattrs, optional secluded-args, iconv, prealloc, stop-at, no crtimes
Optimizations:
    SIMD-roll, no asm-roll, openssl-crypto, no asm-MD5
Checksum list:
    xxh128 xxh3 xxh64 (xxhash) md5 md4 sha1 none
Compress list:
    zstd lz4 zlibx zlib none
Daemon auth list:
    sha512 sha256 sha1 md5 md4

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
```

 and then, my
and error is : 
```

alexandre@alexandre-Matebook:~/Documents/AnalyticaTechCode/ansible$ ansible-playbook playbook.yml --ask-pass 
SSH password: 
BECOME password[defaults to SSH password]: 

PLAY [servers] ************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************************************
ok: [ubuntu]

TASK [Ensure directory exists] ********************************************************************************************************************************************************************************************
ok: [ubuntu]

TASK [Install rsync] ******************************************************************************************************************************************************************************************************
changed: [ubuntu]

TASK [Synchronize project files] ******************************************************************************************************************************************************************************************
TASK [Synchronize project files] ******************************************************************************************************************************************************************************************
alexandre@xx.xx.xx.xx's password: 
fatal: [ubuntu -> localhost]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --exclude=.git --exclude=var/cache/* --exclude=var/log/* --exclude=.env.local --exclude=vendor/ --exclude=node_modules/ --exclude=ansible/ --out-format='<<CHANGED>>%i %n%L' /home/alexandre/Documents/AnalyticaTechCode/ alexandre@xx.xx.xx.xx.xx:/var/www/AnalyticaTechCode", "msg": "Warning: Permanently added 'xx.xx.xx.xx' (ED25519) to the list of known hosts.\r\nsudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper\nsudo: a password is required\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at io.c(231) [sender=3.3.0-21-g9615a249]\n", "rc": 12}

PLAY RECAP ****************************************************************************************************************************************************************************************************************
ubuntu                     : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   



alexandre@alexandre-Matebook:~/Documents/AnalyticaTechCode/ansible$ 
```
my ansible version is  : 

```
alexandre@alexandre-Matebook:~/Documents/AnalyticaTechCode/ansible$ ansible --version
ansible [core 2.16.3]
  config file = /home/alexandre/Documents/AnalyticaTechCode/ansible/ansible.cfg
  configured module search path = ['/home/alexandre/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/alexandre/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
alexandre@alexandre-Matebook:~/Documents/AnalyticaTechCode/ansible$ 

```
could you help me ?
